# -*- coding: utf-8 -*-
"""Salinan dari MODEL_CAPSTONE PROJECT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aLhp4TXVHhA8aVAiraEqkUcBBPSLoN60
"""

Dataset = {
    "Dataset_12" : 
    {
    "saya":"aku",
    "makan":"mangan",
    "nasi":"sego",
    "minum":"ngombe",
    "air":"banyu",},
    "Dataset_21" : 
    {
    "aku":"saya",
    "mangan":"makan",
    "sego":"nasi",
    "ngombe":"minum",
    "banyu":"air"}
}

def translate_bahasa(teks, dataset):
  text_list=[]
  for word in teks.split():
    if word in dataset:
      word = word.replace(word, str(dataset[word]))
      text_list.append(word)
    else:
      text_list.append(word)
  teks=' '.join(map(str, text_list))
  return teks

input_teks = "kulo ngombe banyu"
bahasa = Dataset["Dataset_"+"21"]
print(translate_bahasa(input_teks, bahasa))